### ISSUE TITLE
Can I use this solution for Xiaomi r2d?

### ISSUE THREAD

**Issue by stanislav-ostapenko** [RicherMans/XiaomiVPN#1]
http://www.gearbest.com/networking-communication/pp_197064.html

**Comment by RicherMans** [comment]
Hey there, well I didn't test the code for a long time, but basically as long as u install OpenWRT on the thing shouldnt be a big deal.
Btw I never completely finished the code, sorry. But the manual is still - halfway - okay.

**Comment by stanislav-ostapenko** [comment]
@RicherMans Thank you for your prompt reply.
